import { Raleway } from 'next/font/google';
import { HeroProvider } from '@/providers/HeroProvider';
import StoreProvider from '@/providers/StoreProvider.jsx';
import './globals.css';
import './mystyle.scss';

const raleway = Raleway({
	weight: ['400', '500', '600', '700'],
	subsets: ['latin'],
});

export const metadata = {
	title: 'Muro de Recuerdos',
	description: 'Generated by Pattern',
};

export default function RootLayout(props) {
	const { children } = props;
	return (
		<html lang="es">
			<body className={`${raleway.className} antialiased`}>
				<HeroProvider>
					<StoreProvider>{children}</StoreProvider>
				</HeroProvider>
			</body>
		</html>
	);
}
