import { Raleway } from 'next/font/google';
import { HeroProvider } from '@/providers/HeroProvider';
import StoreProvider from '@/providers/StoreProvider.jsx';
import './globals.css';
import './mystyle.scss';
import Container from '@/components/container/Container';
import NavbarApp from '@/components/ui/NavBar';
import SessionWrapper from '@/providers/SessionWraper';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const raleway = Raleway({
	weight: ['400', '500', '600', '700'],
	subsets: ['latin'],
});

export const metadata = {
	title: 'Reclutamiento Pattern',
	description: 'Generated by Pattern',
};

export default function RootLayout(props) {
	const { children } = props;
	return (
		<html lang="es">
			<body className={`${raleway.className} antialiased flex flex-col min-h-screen`}>
				<SessionWrapper>
					<HeroProvider>
						<StoreProvider>
							{' '}
							<NavbarApp />
							<Container>
								{children}
								<ToastContainer position="bottom-right" autoClose={3000} />
							</Container>
						</StoreProvider>
					</HeroProvider>
				</SessionWrapper>
			</body>
		</html>
	);
}
